spring:
  data:
    elasticsearch:
      cluster-name: es-cluster
      clusterNodes: 192.168.1.100:9300,192.168.1.100:9300,192.168.1.100:9300
      repositories:
        enabled: true
server:
  port: 8888